/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardList: typeof import('./src/components/CardList.vue')['default']
    EditLocationForm: typeof import('./src/components/EditLocationForm.vue')['default']
    LocationCard: typeof import('./src/components/LocationCard.vue')['default']
    LocationForm: typeof import('./src/components/LocationForm.vue')['default']
    LottieAnimation: typeof import('./src/components/LottieAnimation.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    QrReader: typeof import('./src/components/QrReader.vue')['default']
    ReportReviewForm: typeof import('./src/components/ReportReviewForm.vue')['default']
    ReviewForm: typeof import('./src/components/ReviewForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
